Repository py-mine/PyMine, pull requests merged in 2021-01, with the labels that each got.

#159 add pack_trade of Buffer
  src/types/buffer.py
Labels: Enhancement

#164 Add optional field handling methods and remove bool handling methods
  src/types/buffer.py
  src/types/packets/play/advancement.py
  src/types/packets/play/block.py
  src/types/packets/play/chat.py
  src/types/packets/play/command_block.py
  src/types/packets/play/crafting.py
  src/types/packets/play/difficulty.py
  src/types/packets/play/effect.py
  src/types/packets/play/entity.py
  src/types/packets/play/item.py
  src/types/packets/play/player.py
  src/types/packets/play/structure_block.py
  src/types/packets/play/vehicle.py
  src/types/packets/play/window.py
Labels: Enhancement

#167 Merge 112-play to main
  src/types/packets/play/advancement.py
  src/types/packets/play/block.py
  src/types/packets/play/boss.py
  src/types/packets/play/chat.py
  src/types/packets/play/chunk.py
  src/types/packets/play/cooldown.py
  src/types/packets/play/crafting.py
  src/types/packets/play/entity.py
  src/types/packets/play/explosion.py
  src/types/packets/play/map.py
  src/types/packets/play/particle.py
  src/types/packets/play/player.py
  src/types/packets/play/plugin_msg.py
  src/types/packets/play/scoreboard.py
  src/types/packets/play/sign.py
  src/types/packets/play/sounds.py
  src/types/packets/play/spawn.py
  src/types/packets/play/structure_block.py
  src/types/packets/play/time.py
  src/types/packets/play/vehicle.py
  src/types/packets/play/window.py
Labels: Enhancement

#180 Cleanup
  pymine/api/__init__.py
  pymine/data/config.py
  pymine/data/packet_map.py
  pymine/logic/handle/login.py
  pymine/logic/handle/status.py
  pymine/server.py
  pymine/types/buffer.py
  pymine/types/chat.py
  pymine/types/registry.py
  pymine/util/encryption.py
  pymine/util/share.py
Labels: Enhancement

#182 Add plugins API
  .gitignore
  plugins/FAP/__init__.py
  plugins/example/__init__.py
  pymine/api/__init__.py
  pymine/data/config.py
  pymine/logic/handle/login.py
  pymine/server.py
  pymine/util/logging.py
Labels: Enhancement

#187 Merge cleanup changes (and some new packets) to main
  .gitignore
  plugins/FAP/__init__.py
  pymine/data/packet_map.py
  pymine/server.py
  pymine/types/buffer.py
  pymine/types/packets/play/block.py
  pymine/types/packets/play/entity.py
  pymine/types/packets/play/player.py
  pymine/types/packets/play/recipe.py
  pymine/types/packets/play/resource_pack.py
  pymine/types/packets/play/scoreboard.py
  pymine/types/packets/play/sounds.py
  pymine/util/data_gen.py
  server-icon.png
Labels: Enhancement

#189 Add some missing Buffer methods
  pymine/types/buffer.py
  pymine/types/packets/play/world.py
Labels: Enhancement

#191 Merge StreamReader and StreamWriter into a singular Stream object
  pymine/api/__init__.py
  pymine/logic/handle/handshaking.py
  pymine/logic/handle/login.py
  pymine/logic/handle/status.py
  pymine/server.py
  pymine/types/stream.py
  pymine/util/encryption.py
Labels: Enhancement

#198 Fetch primary local address if addr is None
  pymine/server.py
Labels: Bug, Enhancement

#202 Plugin API and management cleanup
  plugins/FAP/__init__.py
  pymine/api/__init__.py
  pymine/api/api.py
  pymine/util/path.py
Labels: Enhancement

#203 test
  pymine/types/packets/play/entity.py
Labels: Invalid

#206 OOPIFY / 192-restructure
  pymine/__main__.py
  pymine/api/__init__.py
  pymine/api/api.py
  pymine/api/chat.py
  pymine/api/commands.py
  pymine/api/events.py
  pymine/api/packet.py
  pymine/api/player.py
  pymine/api/server.py
  pymine/api/tasks.py
  pymine/data/config.py
  pymine/data/packet_map.py
  pymine/logic/cmds/pymine_util.py
  pymine/logic/cmds/stop.py
  pymine/logic/commands.py
  pymine/logic/handle/handshaking.py
  pymine/logic/packet/handshaking.py
  pymine/logic/packet/login.py
  pymine/logic/packet/status.py
  pymine/server.py
  pymine/types/buffer.py
  pymine/util/config.py
Labels: Enhancement

#209 205 Concurrent Plugin Updating
  pymine/api/__init__.py
  pymine/util/config.py
  pymine/util/misc.py
Labels: Enhancement

#215 refactor gen comp with .join() to list comp
  pymine/types/buffer.py
  pymine/types/chat.py
  pymine/types/packets/play/chat.py
  pymine/types/packets/play/crafting.py
  pymine/types/packets/play/entity.py
  pymine/types/packets/play/player.py
  pymine/types/packets/play/recipe.py
  pymine/types/packets/play/statistics.py
  pymine/types/packets/play/team.py
  pymine/types/packets/play/vehicle.py
  pymine/types/packets/play/villager.py
  pymine/types/packets/play/window.py
  pymine/util/logging.py
Labels: Enhancement

#226 Simplify packet handlers + packet handler handling
  pymine/api/__init__.py
  pymine/logic/packet/handshaking.py
  pymine/logic/packet/login.py
  pymine/logic/packet/status.py
  pymine/server.py
Labels: Enhancement

#236 NBT Lib
  .gitignore
  pymine/types/buffer.py
  pymine/types/nbt.py
  requirements.txt
Labels: Enhancement

#240 Update buffer.py and requirements.txt
  pymine/logic/play.py
  pymine/types/buffer.py
  pymine/types/nbt.py
  pymine/types/packets/play/block.py
  pymine/types/packets/play/chunk.py
  pymine/types/packets/play/entity.py
  pymine/types/packets/play/player.py
  pymine/types/packets/play/scoreboard.py
  requirements.txt
Labels: Enhancement

#241 Add modifier handler methods to Buffer of buffer.py
  pymine/types/buffer.py
Labels: Enhancement

#247 Merge tests to main to keep pytest from breaking on branches other than tests
  .github/workflows/flake8.yml
  .github/workflows/pytest.yml
  .gitignore
  tests/sample_nbt/bigtest.nbt
  tests/sample_nbt/level.dat
  tests/sample_nbt/nantest.nbt
  tests/test_buffer.py
  tests/test_nbt.py
Labels: Enhancement

#252 249 Plugin dependencies
  .gitignore
  pymine/api/__init__.py
Labels: Enhancement
